### ISSUE TITLE
the demo doesn't work

### ISSUE THREAD

**Issue by vingol** [slacgismo/StatisticalClearSky#19]
obtaining initial value of component r0
obtaining weights
Traceback (most recent call last):
  File "/Users/mayuan/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-f8197e3aee13>", line 1, in <module>
    runfile('/Users/mayuan/Downloads/projects/second_year/data_jilin/SCSF.py', wdir='/Users/mayuan/Downloads/projects/second_year/data_jilin')
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/mayuan/Downloads/projects/second_year/data_jilin/SCSF.py", line 13, in <module>
    iterative_fitting.execute(is_degradation_calculated=False)
  File "/Users/mayuan/anaconda3/lib/python3.6/site-packages/statistical_clear_sky/algorithm/iterative_fitting.py", line 74, in execute
    non_neg_constraints=non_neg_constraints, verbose=verbose)
  File "/Users/mayuan/anaconda3/lib/python3.6/site-packages/statistical_clear_sky/algorithm/iterative_fitting.py", line 156, in _minimize_objective
    sum_components=False)
  File "/Users/mayuan/anaconda3/lib/python3.6/site-packages/statistical_clear_sky/algorithm/iterative_fitting.py", line 262, in _calculate_objective
    l_cs_value[2:, :]).dot(weights_w2), 'fro')
ValueError: shapes (2,4) and (6,6) not aligned: 4 (dim 1) != 6 (dim 0)

**Comment by mikofski** [comment]
I get the same error for the first example:
```
ValueError: shapes (2,4) and (6,6) not aligned: 4 (dim 1) != 6 (dim 0)     
```
